"""
Django settings for help_for_friends project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')dh+=-1d*ie2i5(v-1rs19m!)9kaz6=xefbc+r48#t8ka+cozr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app',
    'fundraisers',
    'organizations',
    'profiles',
    'tinymce',
    #'billings',
    #'admin',
    'bootstrap3',
    'django_summernote',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'help_for_friends.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 'templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'help_for_friends.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.crowdfunding'),
    }
}

AUTH_USER_MODEL='profiles.User'
LOGIN_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/customs'),
    os.path.join(BASE_DIR, 'static/app'),
    os.path.join(BASE_DIR, 'static/about'),
    os.path.join(BASE_DIR, 'static/fundraisers/'),
    os.path.join(BASE_DIR, 'static/registrations/'),
    os.path.join(BASE_DIR, 'static/froala'),
)

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIAFILES_DIRS = (
    os.path.join(BASE_DIR, "media/images"),
    #'/var/www/static/',
)

#===============================Global Model Choices ============================
BENEFICIARY_TYPE=(
    ('personal', 'Personal'),
    ('ngo', "NGO/Non-Profit Company"),
)

FUNDRAISER_TYPE=(
    ('non_ngo', 'Individual/Non-NGO'),
    ('ngo', 'NGO'),
)

FUNDRAISER_STATUS = (
    ('draft', 'Draft'),
    ('approved', 'Approved'),
    ('published', 'Published'),
    ('closed', 'Closed'),
    ('blocked', 'Blocked'),
)

FUNDRAISER_CAUSES=(
    ('animal_welfare', 'Animal Welfare'),
    ('education', 'Education'),
    ('medical', 'Medical'),
    ('farmers_welcome', 'Farmers Welfare'),
    ('water_conservation', 'Water Conservation'),
    ('women_empowerment', 'Women Empowerment'),
    ('organic_farming', 'Organic Agriculture/Farming'),
)

DOCUMENT_CHOICES=(
    ('draft', 'Draft'),
    ('pending', 'Pending'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected'),
)

ADDRESS_TYPES=(
    ('passport', 'Passport'),
    ('driver_license' ,'Driver License'),
    ('electricity_bill', 'Electricity Bill'),
    ('bank_statement', 'Bank Statement'),
    ('phone_bill', 'Phone Bill MTNL/BSNL'),
    ('voter_id', 'Voter ID Card'),
    ('shop_license', 'Shop License'),
)