# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
