# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_auto_20171213_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='full_description',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/fundraisers/titles/'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='video_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
