# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 13:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_auto_20171215_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='full_description',
            field=tinymce.models.HTMLField(max_length=100000),
        ),
    ]
