# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0005_auto_20171215_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='causes',
            field=models.CharField(blank=True, choices=[(b'animal_welfare', b'Animal Welfare'), (b'education', b'Education'), (b'medical', b'Medical'), (b'farmers_welcome', b'Farmers Welfare'), (b'water_conservation', b'Water Conservation'), (b'women_empowerment', b'Women Empowerment'), (b'organic_farming', b'Organic Agriculture/Farming')], default='Please Select Your Cause', max_length=20, verbose_name='Your Fundraiser Cause'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='city',
            field=models.CharField(help_text='The city where your campaign will be run or where you have your highest audience', max_length=100, verbose_name='Your City'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='end_date',
            field=models.DateTimeField(help_text='date till which the campaign will be run (ranges b/w  3 monthns)'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='goal_amount',
            field=models.PositiveIntegerField(default=2000, help_text='The target amount for the cause. min. is Rs. 2000/-'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='short_description',
            field=models.CharField(help_text='describe your fundraiser needs wisely within 500 characters.', max_length=250, verbose_name='Please Describe Your Fundraiser Details'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='title',
            field=models.CharField(help_text='Choose Fundraise Title Wisely e.g.- Help me imporve water conservation in rajasthan', max_length=150, verbose_name='Your Fundraiser Title'),
        ),
    ]
