# Generated by Django 2.0 on 2017-12-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0006_auto_20171215_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRaiserReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=256)),
                ('product', models.CharField(blank=True, max_length=120, null=True)),
                ('delivering_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='beneficiary_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('ngo', 'NGO/Non-Profit Company')], default='personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='campaign_type',
            field=models.CharField(choices=[('non_ngo', 'Individual/Non-NGO'), ('ngo', 'NGO')], default='non_ngo', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='causes',
            field=models.CharField(blank=True, choices=[('animal_welfare', 'Animal Welfare'), ('education', 'Education'), ('medical', 'Medical'), ('farmers_welcome', 'Farmers Welfare'), ('water_conservation', 'Water Conservation'), ('women_empowerment', 'Women Empowerment'), ('organic_farming', 'Organic Agriculture/Farming')], default='Please Select Your Cause', max_length=20, verbose_name='Your Fundraiser Cause'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('closed', 'Closed'), ('blocked', 'Blocked')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='fundraiserreward',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='fundraisers.FundRaiser'),
        ),
    ]
