# Generated by Django 2.0 on 2017-12-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraisers', '0007_auto_20171216_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.PositiveSmallIntegerField(choices=[(1, 'Animal'), (3, 'Relative'), (3, 'Organization'), (4, 'Individual Person/Needy Person')], default=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/beneficiaries/')),
                ('full_name', models.CharField(max_length=100)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraisers.FundRaiser')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
