# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('custom_url', models.URLField(max_length=250)),
                ('causes_supported', models.CharField(blank=True, choices=[(b'animal_welfare', b'Animal Welfare'), (b'education', b'Education'), (b'medical', b'Medical'), (b'farmers_welcome', b'Farmers Welfare'), (b'water_conservation', b'Water Conservation'), (b'women_empowerment', b'Women Empowerment'), (b'organic_farming', b'Organic Agriculture/Farming')], max_length=20)),
                ('logo_image', models.ImageField(upload_to='media/uploads/organizations/')),
                ('address', models.TextField(max_length=500)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=13, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('address_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orginizations', to='app.AddressDetail')),
                ('bank_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orginizations', to='app.BankDetail')),
                ('bank_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='app.BankStatementDetail')),
                ('gst_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='app.GSTDetail')),
                ('members', models.ManyToManyField(related_name='organization_members', to=settings.AUTH_USER_MODEL)),
                ('pan_card_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orginizations', to='app.PanCardDetail')),
                ('social_contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_profiles', to='app.SocialProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEightyGDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=500)),
                ('registration_no', models.CharField(max_length=50, verbose_name='80G Certification Reg. No.')),
                ('registration_date', models.DateTimeField(verbose_name='80G Registration Date')),
                ('date_of_incorporation', models.DateTimeField(verbose_name='Date of incorporation')),
                ('place_of_incorporation', models.CharField(max_length=100)),
                ('pan_card_number', models.CharField(max_length=50)),
                ('aggreed', models.BooleanField(default=False, verbose_name="The information submitted herewith above is correct and true to my knowledge. All the documents uploaded are genuine and valid. I hereby agree to inform Ketto in case of any changes in my organisation's status.")),
                ('declared', models.BooleanField(default=False, verbose_name="I hereby declare that I have read and agree to adhere to Ketto's terms of use, FAQs, pricing and privacy policy. ")),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_eighty_g_details', to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRegistrationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_incorporation', models.DateTimeField()),
                ('certificate_image', models.ImageField(upload_to='media/uploads/organizations/legel_documents/')),
                ('eighty_g_certificate', models.ImageField(null=True, upload_to='media/uploads/organizations/legel_documents/')),
                ('society_deed', models.ImageField(null=True, upload_to='media/uploads/organizations/legel_documents/')),
                ('trust_deed', models.ImageField(null=True, upload_to='media/uploads/organizations/legel_documents/')),
                ('memorandum_of_articles', models.ImageField(null=True, upload_to='media/uploads/organizations/legel_documents/')),
                ('memorandum_of_association', models.ImageField(null=True, upload_to='media/uploads/organizations/legel_documents/')),
                ('aggreed', models.BooleanField(default=False, verbose_name="The information submitted herewith above is correct and true to my knowledge. All the documents uploaded are genuine and valid. I hereby agree to inform Ketto in case of any changes in my organisation's status.")),
                ('declared', models.BooleanField(default=False, verbose_name="I hereby declare that I have read and agree to adhere to Ketto's terms of use, FAQs, pricing and privacy policy. ")),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='organizations.Organization')),
            ],
        ),
    ]
