# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='full_name',
        ),
    ]
