# Generated by Django 2.0 on 2017-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20171213_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='causes_supported',
            field=models.CharField(blank=True, choices=[('animal_welfare', 'Animal Welfare'), ('education', 'Education'), ('medical', 'Medical'), ('farmers_welcome', 'Farmers Welfare'), ('water_conservation', 'Water Conservation'), ('women_empowerment', 'Women Empowerment'), ('organic_farming', 'Organic Agriculture/Farming')], max_length=20),
        ),
    ]
