# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[(b'passport', b'Passport'), (b'driver_license', b'Driver License'), (b'electricity_bill', b'Electricity Bill'), (b'bank_statement', b'Bank Statement'), (b'phone_bill', b'Phone Bill MTNL/BSNL'), (b'voter_id', b'Voter ID Card'), (b'shop_license', b'Shop License')], help_text='Choose an address proof from the dropdown above. NGO name should be mentioned in the bill you submit', max_length=20, null=True)),
                ('image', models.ImageField(upload_to='media/uploads/organizations/documents/')),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'pending', b'Pending'), (b'approved', b'Approved'), (b'rejected', b'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('addition_info', models.CharField(blank=True, help_text='Such as Routing No, Sort Code, etc', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Cancelled cheque / bank statement / first page of your Non FCRA bank account passbook', help_text='Please note that the Account name, Account number and Branch IFSC code should be clearly mentioned in the document you choose to upload.', max_length=150)),
                ('image', models.ImageField(upload_to='media/uploads/organizations/documents/')),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'pending', b'Pending'), (b'approved', b'Approved'), (b'rejected', b'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GSTDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(help_text='GST Registered Name', max_length=100)),
                ('gstin', models.CharField(help_text='GSTIN Number', max_length=30)),
                ('registered_address', models.CharField(help_text='Registered Address under GST', max_length=300)),
                ('state', models.CharField(help_text='Location of your GST registration', max_length=30)),
                ('phone_no', models.CharField(help_text='Registered Contact Detials for GST (Mobile Number)', max_length=13)),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'pending', b'Pending'), (b'approved', b'Approved'), (b'rejected', b'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PanCardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/uploads/organizations/documents/')),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'pending', b'Pending'), (b'approved', b'Approved'), (b'rejected', b'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_link', models.URLField(max_length=250, null=True)),
                ('google_plus_link', models.URLField(max_length=250, null=True)),
                ('facebook_link', models.URLField(max_length=250, null=True)),
                ('linkedin_link', models.URLField(max_length=250, null=True)),
            ],
        ),
    ]
