# Generated by Django 2.0 on 2017-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetail',
            name='address_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('electricity_bill', 'Electricity Bill'), ('bank_statement', 'Bank Statement'), ('phone_bill', 'Phone Bill MTNL/BSNL'), ('voter_id', 'Voter ID Card'), ('shop_license', 'Shop License')], help_text='Choose an address proof from the dropdown above. NGO name should be mentioned in the bill you submit', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatementdetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gstdetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pancarddetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
